name: Event Management System CI/CD

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /opt/event-management-system/app

            git fetch origin main
            git reset --hard origin/main

            docker compose build
            docker compose up -d

            docker compose ps
